---
title: "omerf case study 1 rev 2"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("C:/Users/lidia/OneDrive - Politecnico di Milano/Desktop/Omerf_rev2/risultati chiara/risultati_lidia.RData")

#load("C:/Users/lidia/OneDrive - Politecnico di Milano/Desktop/Omerf_rev2/risultati chiara/risultati_lidia_clm_new.RData")
```

```{r}
# Cohen's Weighted Kappa per risposta ordinale.
# weights = "quadratic" penalizza maggiormente gli errori lontani;
# usare weights = "linear" se si desidera una penalizzazione lineare.
weighted_kappa_safe <- function(y_true, y_pred, lev, weights = "quadratic") {
  y_true <- factor(y_true, levels = lev, ordered = TRUE)
  y_pred <- factor(y_pred, levels = lev, ordered = TRUE)
  
  tab <- table(y_true, y_pred)
  n <- sum(tab)
  K <- length(lev)
  
  if (n == 0 || K < 2) {
    return(NA_real_)
  }
  
  d <- abs(row(tab) - col(tab))
  if (weights == "linear") {
    W <- d / (K - 1)
  } else if (weights == "quadratic") {
    W <- (d / (K - 1))^2
  } else {
    stop("weights deve essere 'linear' oppure 'quadratic'")
  }
  
  O <- tab / n
  E <- outer(rowSums(tab), colSums(tab)) / n^2
  
  den <- sum(W * E)
  if (den == 0) {
    return(NA_real_)
  }
  
  1 - sum(W * O) / den
}
```

```{r}
# Confusion matrix quadrata con tutti i livelli.
confusion_full <- function(y_true, y_pred, lev) {
  tab <- table(
    factor(y_true, levels = lev, ordered = TRUE),
    factor(y_pred, levels = lev, ordered = TRUE)
  )
  dimnames(tab) <- list(observed = lev, predicted = lev)
  tab
}
```

```{r}
#y_omerf_t.0=y_omerf_clm_t.0
#y_omerf_t.1=y_omerf_clm_t.1
```

```{r}
# RMSE e MAE sulla scala ordinale numerica
rmse_safe <- function(y_true, y_pred) {
  sqrt(mean((as.numeric(y_true) - as.numeric(y_pred))^2, na.rm = TRUE))
}

mae_safe <- function(y_true, y_pred) {
  mean(abs(as.numeric(y_true) - as.numeric(y_pred)), na.rm = TRUE)
}

# Precision e recall per classe da confusion matrix
class_precision_recall <- function(cm) {
  precision <- diag(cm) / colSums(cm)
  recall    <- diag(cm) / rowSums(cm)
  
  precision[is.nan(precision)] <- NA_real_
  recall[is.nan(recall)] <- NA_real_
  
  data.frame(
    class = rownames(cm),
    precision = as.numeric(precision),
    recall = as.numeric(recall),
    row.names = NULL
  )
}
```


```{r}
models <- c("clm", "clmm", "ordforest", "omerf")
dgps <- c("DGP0", "DGP1")

pred_list <- list(
  DGP0 = list(
    clm       = y_clm_t.0,
    clmm      = y_clmm_t.0,
    ordforest = y_ord_t.0,
    omerf     = y_omerf_t.0
  ),
  DGP1 = list(
    clm       = y_clm_t.1,
    clmm      = y_clmm_t.1,
    ordforest = y_ord_t.1,
    omerf     = y_omerf_t.1
  )
)

# Tabelle richieste dal revisore
results.rmse <- matrix(NA_real_, nrow = length(dgps), ncol = length(models),
                       dimnames = list(dgps, models))
results.mae <- matrix(NA_real_, nrow = length(dgps), ncol = length(models),
                      dimnames = list(dgps, models))
results.wkappa <- matrix(NA_real_, nrow = length(dgps), ncol = length(models),
                         dimnames = list(dgps, models))

# Liste per supplementary material
confusion_matrices <- list()
classwise_precision_recall <- list()

for (dgp in dgps) {
  confusion_matrices[[dgp]] <- list()
  classwise_precision_recall[[dgp]] <- list()
  
  for (model in models) {
    y_pred <- as.numeric(pred_list[[dgp]][[model]])
    
    cm <- confusion_full(y_test, y_pred, lev)
    
    results.rmse[dgp, model] <- rmse_safe(y_test, y_pred)
    results.mae[dgp, model] <- mae_safe(y_test, y_pred)
    results.wkappa[dgp, model] <- weighted_kappa_safe(
      y_true = y_test,
      y_pred = y_pred,
      lev = lev,
      weights = "quadratic"
    )
    
    confusion_matrices[[dgp]][[model]] <- cm
    
    tmp <- class_precision_recall(cm)
    tmp$DGP <- dgp
    tmp$model <- model
    
    classwise_precision_recall[[dgp]][[model]] <- tmp
  }
}

classwise_precision_recall_table <- do.call(
  rbind,
  unlist(classwise_precision_recall, recursive = FALSE)
)

results.rmse
results.mae
results.wkappa
classwise_precision_recall_table
confusion_matrices
```


```{r}

library(pdfCluster)
library(psych)
results.acc=matrix(nrow=2, ncol=4, data=rep(0,8))
results.mse=matrix(nrow=2, ncol=4, data=rep(0,8))
results.oc=matrix(nrow=2, ncol=4, data=rep(0,8))
results.ari=matrix(nrow=2, ncol=4, data=rep(0,8))
results.ck=matrix(nrow=2, ncol=4, data=rep(0,8))
results.newi=matrix(nrow=2, ncol=4, data=rep(0,8))
colnames(results.acc)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.mse)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.oc)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.ari)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.ck)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.newi)=c('clm', 'clmm','ordforest', 'omerf')

y_test=as.numeric(y_test_orig)
y_test_newi=as.numeric(y_test_orig)
lev=levels(clm.data$y)


results.acc[1,1]=sum(y_test==as.numeric(y_clm_t.0))/length(y_test)
results.mse[1,1]=mean((y_test - as.numeric(y_clm_t.0))^2)
cm_clm <- table(y_test, as.numeric(y_clm_t.0))
cm_clm
num_classes_clm <- max(nrow(cm_clm), ncol(cm_clm))
cm_clm2 <- matrix(0, nrow = num_classes_clm, ncol = num_classes_clm)
rownames(cm_clm2) <- colnames(cm_clm2) <- lev
cm_clm2[rownames(cm_clm), colnames(cm_clm)] <- cm_clm[rownames(cm_clm), colnames(cm_clm)]
results.oc[1,1]=OrdinalClassificationIndex(cm_clm2, dim(cm_clm2)[1])
results.ari[1,1]=adj.rand.index(y_test, as.numeric(y_clm_t.0))
results.ck[1,1]=cohen.kappa(x=cbind(y_test,as.numeric(y_clm_t.0)))$kappa
results.newi[1,1]=newindex(mu_clm_t.0,y_test_newi,num_classes_clm)$norm.index


results.acc[2,1]=sum(y_test==as.numeric(y_clm_t.1))/length(y_test)
results.mse[2,1]=mean((y_test - as.numeric(y_clm_t.1))^2)
cm_clm <- table(y_test, as.numeric(y_clm_t.1))
cm_clm
num_classes_clm <- max(nrow(cm_clm), ncol(cm_clm))
cm_clm2 <- matrix(0, nrow = num_classes_clm, ncol = num_classes_clm)
rownames(cm_clm2) <- colnames(cm_clm2) <- lev
cm_clm2[rownames(cm_clm), colnames(cm_clm)] <- cm_clm[rownames(cm_clm), colnames(cm_clm)]
results.oc[2,1]=OrdinalClassificationIndex(cm_clm2, dim(cm_clm2)[1])
results.ari[2,1]=adj.rand.index(y_test, as.numeric(y_clm_t.1))
results.ck[2,1]=cohen.kappa(x=cbind(y_test,as.numeric(y_clm_t.1)))$kappa
results.newi[2,1]=newindex(mu_clm_t.1,y_test_newi,num_classes_clm)$norm.index


results.acc[1,2]=sum(y_test==as.numeric(y_clmm_t.0))/length(y_test)
results.mse[1,2]=mean((y_test - as.numeric(y_clmm_t.0))^2)
cm_clmm <- table(y_test, as.numeric(y_clmm_t.0))
cm_clmm
num_classes_clmm <- max(nrow(cm_clmm), ncol(cm_clmm))
cm_clmm2 <- matrix(0, nrow = num_classes_clmm, ncol = num_classes_clmm)
rownames(cm_clmm2) <- colnames(cm_clmm2) <- lev
cm_clmm2[rownames(cm_clmm), colnames(cm_clmm)] <- cm_clmm[rownames(cm_clmm), colnames(cm_clmm)]
results.oc[1,2]=OrdinalClassificationIndex(cm_clmm2, dim(cm_clmm2)[1])
results.ari[1,2]=adj.rand.index(y_test, as.numeric(y_clmm_t.0))
results.ck[1,2]=cohen.kappa(x=cbind(y_test,as.numeric(y_clmm_t.0)))$kappa
results.newi[1,2]=newindex(mu_clmm_t.0,y_test_newi,num_classes_clmm)$norm.index


results.acc[2,2]=sum(y_test==as.numeric(y_clmm_t.1))/length(y_test)
results.mse[2,2]=mean((y_test - as.numeric(y_clmm_t.1))^2)
cm_clmm <- table(y_test, as.numeric(y_clmm_t.1))
cm_clmm
num_classes_clmm <- max(nrow(cm_clmm), ncol(cm_clmm))
cm_clmm2 <- matrix(0, nrow = num_classes_clmm, ncol = num_classes_clmm)
rownames(cm_clmm2) <- colnames(cm_clmm2) <- lev
cm_clmm2[rownames(cm_clmm), colnames(cm_clmm)] <- cm_clmm[rownames(cm_clmm), colnames(cm_clmm)]
results.oc[2,2]=OrdinalClassificationIndex(cm_clmm2, dim(cm_clmm2)[1])
results.ari[2,2]=adj.rand.index(y_test, as.numeric(y_clmm_t.1))
results.ck[2,2]=cohen.kappa(x=cbind(y_test,as.numeric(y_clmm_t.1)))$kappa
results.newi[2,2]=newindex(mu_clmm_t.1,y_test_newi,num_classes_clmm)$norm.index


results.acc[1,3]=sum(y_test==as.numeric(y_ord_t.0))/length(y_test)
results.mse[1,3]=mean((y_test - as.numeric(y_ord_t.0))^2)
cm_ord <- table(y_test, as.numeric(y_ord_t.0))
cm_ord
num_classes_ord <- max(nrow(cm_ord), ncol(cm_ord))
cm_ord2 <- matrix(0, nrow = num_classes_ord, ncol = num_classes_ord)
rownames(cm_ord2) <- colnames(cm_ord2) <- lev
cm_ord2[rownames(cm_ord), colnames(cm_ord)] <- cm_ord[rownames(cm_ord), colnames(cm_ord)]
results.oc[1,3]=OrdinalClassificationIndex(cm_ord2, dim(cm_ord2)[1])
results.ari[1,3]=adj.rand.index(y_test, as.numeric(y_ord_t.0))
results.ck[1,3]=cohen.kappa(x=cbind(y_test,as.numeric(y_ord_t.0)))$kappa
results.newi[1,3]=newindex(mu_ord_t.0,y_test_newi,num_classes_ord)$norm.index


results.acc[2,3]=sum(y_test==as.numeric(y_ord_t.1))/length(y_test)
results.mse[2,3]=mean((y_test - as.numeric(y_ord_t.1))^2)
cm_ord <- table(y_test, as.numeric(y_ord_t.1))
cm_ord
num_classes_ord <- max(nrow(cm_ord), ncol(cm_ord))
cm_ord2 <- matrix(0, nrow = num_classes_ord, ncol = num_classes_ord)
rownames(cm_ord2) <- colnames(cm_ord2) <- lev
cm_ord2[rownames(cm_ord), colnames(cm_ord)] <- cm_ord[rownames(cm_ord), colnames(cm_ord)]
results.oc[2,3]=OrdinalClassificationIndex(cm_ord2, dim(cm_ord2)[1])
results.ari[2,3]=adj.rand.index(y_test, as.numeric(y_ord_t.1))
results.ck[2,3]=cohen.kappa(x=cbind(y_test,as.numeric(y_ord_t.1)))$kappa
results.newi[2,3]=newindex(mu_ord_t.1,y_test_newi,num_classes_ord)$norm.index


results.acc[1,4]=sum(y_test==as.numeric(y_omerf_t.0))/length(y_test)
results.mse[1,4]=mean((y_test - as.numeric(y_omerf_t.0))^2)
cm_omerf <- table(y_test, as.numeric(y_omerf_t.0))
cm_omerf
num_classes_omerf <- max(nrow(cm_omerf), ncol(cm_omerf))
cm_omerf2 <- matrix(0, nrow = num_classes_omerf, ncol = num_classes_omerf)
rownames(cm_omerf2) <- colnames(cm_omerf2) <- lev
cm_omerf2[rownames(cm_omerf), colnames(cm_omerf)] <- cm_omerf[rownames(cm_omerf), colnames(cm_omerf)]
results.oc[1,4]=OrdinalClassificationIndex(cm_omerf2, dim(cm_omerf2)[1])
results.ari[1,4]=adj.rand.index(y_test, as.numeric(y_omerf_t.0))
results.ck[1,4]=cohen.kappa(x=cbind(y_test,as.numeric(y_omerf_t.0)))$kappa
results.newi[1,4]=newindex(mu_omerf_t.0,y_test_newi,num_classes_omerf)$norm.index


results.acc[2,4]=sum(y_test==as.numeric(y_omerf_t.1))/length(y_test)
results.mse[2,4]=mean((y_test - as.numeric(y_omerf_t.1))^2)
cm_omerf <- table(y_test, as.numeric(y_omerf_t.1))
cm_omerf
num_classes_omerf <- max(nrow(cm_omerf), ncol(cm_omerf))
cm_omerf2 <- matrix(0, nrow = num_classes_omerf, ncol = num_classes_omerf)
rownames(cm_omerf2) <- colnames(cm_omerf2) <- lev
cm_omerf2[rownames(cm_omerf), colnames(cm_omerf)] <- cm_omerf[rownames(cm_omerf), colnames(cm_omerf)]
results.oc[2,4]=OrdinalClassificationIndex(cm_omerf2, dim(cm_omerf2)[1])
results.ari[2,4]=adj.rand.index(y_test, as.numeric(y_omerf_t.1))
results.ck[2,4]=cohen.kappa(x=cbind(y_test,as.numeric(y_omerf_t.1)))$kappa
results.newi[2,4]=newindex(mu_omerf_t.1,y_test_newi,num_classes_omerf)$norm.index


results.acc
results.mse
results.oc
results.ari
results.ck
results.newi
```

```{r}
# ============================================================
# PERFORMANCE MEASURES
# ============================================================

library(pdfCluster)
library(psych)

# ------------------------------------------------------------
# 1. Basic objects
# ------------------------------------------------------------

models <- c("clm", "clmm", "ordforest", "omerf")
specifications <- c("without_ESCS", "with_ESCS")

y_test <- as.numeric(y_test_orig)
y_test_newi <- as.numeric(y_test_orig)
lev <- levels(clm.data$y)

# Predictions by model and specification
pred_list <- list(
  without_ESCS = list(
    clm       = y_clm_t.0,
    clmm      = y_clmm_t.0,
    ordforest = y_ord_t.0,
    omerf     = y_omerf_t.0
  ),
  with_ESCS = list(
    clm       = y_clm_t.1,
    clmm      = y_clmm_t.1,
    ordforest = y_ord_t.1,
    omerf     = y_omerf_t.1
  )
)

# Probability matrices needed for the new index
mu_list <- list(
  without_ESCS = list(
    clm       = mu_clm_t.0,
    clmm      = mu_clmm_t.0,
    ordforest = mu_ord_t.0,
    omerf     = mu_omerf_t.0
  ),
  with_ESCS = list(
    clm       = mu_clm_t.1,
    clmm      = mu_clmm_t.1,
    ordforest = mu_ord_t.1,
    omerf     = mu_omerf_t.1
  )
)

# ------------------------------------------------------------
# 2. Helper functions
# ------------------------------------------------------------

rmse_safe <- function(y_true, y_pred) {
  sqrt(mean((as.numeric(y_true) - as.numeric(y_pred))^2, na.rm = TRUE))
}

mae_safe <- function(y_true, y_pred) {
  mean(abs(as.numeric(y_true) - as.numeric(y_pred)), na.rm = TRUE)
}

confusion_full <- function(y_true, y_pred, lev) {
  tab <- table(
    observed = factor(y_true, levels = lev, ordered = TRUE),
    predicted = factor(y_pred, levels = lev, ordered = TRUE)
  )
  tab
}

class_precision_recall <- function(cm) {
  precision <- diag(cm) / colSums(cm)
  recall <- diag(cm) / rowSums(cm)
  
  precision[is.nan(precision)] <- NA_real_
  recall[is.nan(recall)] <- NA_real_
  
  data.frame(
    class = rownames(cm),
    precision = as.numeric(precision),
    recall = as.numeric(recall),
    row.names = NULL
  )
}

weighted_kappa_safe <- function(y_true, y_pred, lev, weights = "quadratic") {
  y_true <- factor(y_true, levels = lev, ordered = TRUE)
  y_pred <- factor(y_pred, levels = lev, ordered = TRUE)
  
  tab <- table(y_true, y_pred)
  n <- sum(tab)
  K <- length(lev)
  
  if (n == 0 || K < 2) {
    return(NA_real_)
  }
  
  d <- abs(row(tab) - col(tab))
  
  if (weights == "linear") {
    W <- d / (K - 1)
  } else if (weights == "quadratic") {
    W <- (d / (K - 1))^2
  } else {
    stop("weights must be 'linear' or 'quadratic'")
  }
  
  O <- tab / n
  E <- outer(rowSums(tab), colSums(tab)) / n^2
  
  den <- sum(W * E)
  
  if (den == 0) {
    return(NA_real_)
  }
  
  1 - sum(W * O) / den
}

confusion_matrix_to_table <- function(cm, specification, model) {
  out <- as.data.frame(as.table(cm))
  names(out) <- c("observed", "predicted", "n")
  out$specification <- specification
  out$model <- model
  out <- out[, c("specification", "model", "observed", "predicted", "n")]
  out
}

# ------------------------------------------------------------
# 3. Empty result matrices
# ------------------------------------------------------------

results.acc <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

results.mse <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

results.rmse <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

results.mae <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

results.oc <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

results.ari <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

results.ck <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

results.wkappa <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

results.newi <- matrix(
  NA_real_,
  nrow = length(specifications),
  ncol = length(models),
  dimnames = list(specifications, models)
)

# Objects for supplementary / class-wise results
confusion_matrices <- list()
classwise_precision_recall <- list()
confusion_matrices_table_list <- list()

# ------------------------------------------------------------
# 4. Compute all performance measures
# ------------------------------------------------------------

for (spec in specifications) {
  
  confusion_matrices[[spec]] <- list()
  classwise_precision_recall[[spec]] <- list()
  
  for (model in models) {
    
    y_pred <- as.numeric(pred_list[[spec]][[model]])
    mu_pred <- mu_list[[spec]][[model]]
    
    cm <- confusion_full(
      y_true = y_test,
      y_pred = y_pred,
      lev = lev
    )
    
    num_classes <- length(lev)
    
    results.acc[spec, model] <- sum(y_test == y_pred) / length(y_test)
    results.mse[spec, model] <- mean((y_test - y_pred)^2)
    results.rmse[spec, model] <- sqrt(results.mse[spec, model])
    results.mae[spec, model] <- mean(abs(y_test - y_pred))
    
    results.oc[spec, model] <- OrdinalClassificationIndex(
      cm,
      dim(cm)[1]
    )
    
    results.ari[spec, model] <- adj.rand.index(
      y_test,
      y_pred
    )
    
    results.ck[spec, model] <- cohen.kappa(
      x = cbind(y_test, y_pred)
    )$kappa
    
    results.wkappa[spec, model] <- weighted_kappa_safe(
      y_true = y_test,
      y_pred = y_pred,
      lev = lev,
      weights = "quadratic"
    )
    
    results.newi[spec, model] <- newindex(
      mu_pred,
      y_test_newi,
      num_classes
    )$norm.index
    
    # Save confusion matrix
    confusion_matrices[[spec]][[model]] <- cm
    
    # Class-wise precision and recall
    tmp <- class_precision_recall(cm)
    tmp$specification <- spec
    tmp$model <- model
    tmp <- tmp[, c("specification", "model", "class", "precision", "recall")]
    
    classwise_precision_recall[[spec]][[model]] <- tmp
    
    # Long-format confusion matrix
    confusion_matrices_table_list[[paste(spec, model, sep = "_")]] <-
      confusion_matrix_to_table(
        cm = cm,
        specification = spec,
        model = model
      )
  }
}

# ------------------------------------------------------------
# 5. Final tables
# ------------------------------------------------------------

classwise_precision_recall_table <- do.call(
  rbind,
  unlist(classwise_precision_recall, recursive = FALSE)
)

confusion_matrices_table <- do.call(
  rbind,
  confusion_matrices_table_list
)

# Overall results in long format
overall_results_table <- data.frame()

for (spec in specifications) {
  tmp <- data.frame(
    specification = spec,
    model = models,
    Accuracy = as.numeric(results.acc[spec, ]),
    MSE = as.numeric(results.mse[spec, ]),
    RMSE = as.numeric(results.rmse[spec, ]),
    MAE = as.numeric(results.mae[spec, ]),
    OCI = as.numeric(results.oc[spec, ]),
    ARI = as.numeric(results.ari[spec, ]),
    Cohen_kappa = as.numeric(results.ck[spec, ]),
    Weighted_kappa = as.numeric(results.wkappa[spec, ]),
    New_index = as.numeric(results.newi[spec, ])
  )
  
  overall_results_table <- rbind(overall_results_table, tmp)
}

# Rounded version for reporting
overall_results_table_rounded <- overall_results_table
overall_results_table_rounded[, 3:ncol(overall_results_table_rounded)] <-
  round(overall_results_table_rounded[, 3:ncol(overall_results_table_rounded)], 3)

classwise_precision_recall_table_rounded <- classwise_precision_recall_table
classwise_precision_recall_table_rounded$precision <-
  round(classwise_precision_recall_table_rounded$precision, 3)
classwise_precision_recall_table_rounded$recall <-
  round(classwise_precision_recall_table_rounded$recall, 3)

# ------------------------------------------------------------
# 6. DGP1 / with_ESCS tables
# ------------------------------------------------------------

dgp1_results <- subset(
  overall_results_table,
  specification == "with_ESCS"
)

dgp1_results_rounded <- dgp1_results
dgp1_results_rounded[, 3:ncol(dgp1_results_rounded)] <-
  round(dgp1_results_rounded[, 3:ncol(dgp1_results_rounded)], 3)

dgp1_classwise <- subset(
  classwise_precision_recall_table,
  specification == "with_ESCS"
)

dgp1_classwise_rounded <- dgp1_classwise
dgp1_classwise_rounded$precision <- round(dgp1_classwise_rounded$precision, 3)
dgp1_classwise_rounded$recall <- round(dgp1_classwise_rounded$recall, 3)

dgp1_confusion_matrices_table <- subset(
  confusion_matrices_table,
  specification == "with_ESCS"
)

# Optional wide table: overall metrics + class-wise precision/recall
dgp1_classwise_wide <- reshape(
  dgp1_classwise,
  idvar = c("specification", "model"),
  timevar = "class",
  direction = "wide"
)

dgp1_full_table <- merge(
  dgp1_results,
  dgp1_classwise_wide,
  by = c("specification", "model")
)

dgp1_full_table_rounded <- dgp1_full_table
numeric_cols <- sapply(dgp1_full_table_rounded, is.numeric)
dgp1_full_table_rounded[, numeric_cols] <-
  round(dgp1_full_table_rounded[, numeric_cols], 3)

# ------------------------------------------------------------
# 7. Print results
# ------------------------------------------------------------

results.acc
results.mse
results.rmse
results.mae
results.oc
results.ari
results.ck
results.wkappa
results.newi

overall_results_table_rounded

classwise_precision_recall_table_rounded

confusion_matrices

confusion_matrices_table

dgp1_results_rounded

dgp1_classwise_rounded

dgp1_confusion_matrices_table

dgp1_full_table_rounded

# ------------------------------------------------------------
# 8. Optional: RMarkdown tables
# ------------------------------------------------------------

knitr::kable(
  overall_results_table_rounded,
  caption = "Overall performance metrics by model and specification"
)

knitr::kable(
  classwise_precision_recall_table_rounded,
  caption = "Class-wise precision and recall by model and specification"
)

knitr::kable(
  dgp1_results_rounded,
  caption = "Overall performance metrics for DGP1 / with ESCS"
)

knitr::kable(
  dgp1_classwise_rounded,
  caption = "Class-wise precision and recall for DGP1 / with ESCS"
)

knitr::kable(
  dgp1_full_table_rounded,
  caption = "Overall and class-wise performance metrics for DGP1 / with ESCS"
)

# ------------------------------------------------------------
# 9. Optional: export tables
# ------------------------------------------------------------

# write.csv(
#   overall_results_table_rounded,
#   "overall_results_table.csv",
#   row.names = FALSE
# )
# 
# write.csv(
#   classwise_precision_recall_table_rounded,
#   "classwise_precision_recall_table.csv",
#   row.names = FALSE
# )
# 
# write.csv(
#   confusion_matrices_table,
#   "confusion_matrices_table.csv",
#   row.names = FALSE
# )
# 
# write.csv(
#   dgp1_results_rounded,
#   "dgp1_results.csv",
#   row.names = FALSE
# )
# 
# write.csv(
#   dgp1_classwise_rounded,
#   "dgp1_classwise_precision_recall.csv",
#   row.names = FALSE
# )
# 
# write.csv(
#   dgp1_full_table_rounded,
#   "dgp1_full_table.csv",
#   row.names = FALSE
# )


```

```{r}
# ============================================================
# Overall precision / recall and class-wise accuracy
# ============================================================

# Overall macro-averaged precision and recall
overall_precision_recall <- function(cm) {
  precision_class <- diag(cm) / colSums(cm)
  recall_class <- diag(cm) / rowSums(cm)
  
  precision_class[is.nan(precision_class)] <- NA_real_
  recall_class[is.nan(recall_class)] <- NA_real_
  
  data.frame(
    overall_precision = mean(precision_class, na.rm = TRUE),
    overall_recall = mean(recall_class, na.rm = TRUE)
  )
}

# Class-wise accuracy
# Here it is computed as the proportion of correctly classified
# observations within each observed class.
classwise_accuracy <- function(cm) {
  acc <- diag(cm) / rowSums(cm)
  acc[is.nan(acc)] <- NA_real_
  
  data.frame(
    class = rownames(cm),
    classwise_accuracy = as.numeric(acc),
    row.names = NULL
  )
}

# Containers
additional_overall_metrics <- data.frame()
additional_classwise_accuracy <- data.frame()

# Compute metrics
for (spec in specifications) {
  for (model in models) {
    
    y_pred <- as.numeric(pred_list[[spec]][[model]])
    
    cm <- table(
      observed = factor(y_test, levels = lev, ordered = TRUE),
      predicted = factor(y_pred, levels = lev, ordered = TRUE)
    )
    
    # Overall precision and recall
    overall_tmp <- overall_precision_recall(cm)
    overall_tmp$specification <- spec
    overall_tmp$model <- model
    overall_tmp <- overall_tmp[
      ,
      c("specification", "model", "overall_precision", "overall_recall")
    ]
    
    additional_overall_metrics <- rbind(
      additional_overall_metrics,
      overall_tmp
    )
    
    # Class-wise accuracy
    class_tmp <- classwise_accuracy(cm)
    class_tmp$specification <- spec
    class_tmp$model <- model
    class_tmp <- class_tmp[
      ,
      c("specification", "model", "class", "classwise_accuracy")
    ]
    
    additional_classwise_accuracy <- rbind(
      additional_classwise_accuracy,
      class_tmp
    )
  }
}

# Rounded versions for LaTeX
additional_overall_metrics_rounded <- additional_overall_metrics
additional_overall_metrics_rounded[, c("overall_precision", "overall_recall")] <-
  round(
    additional_overall_metrics_rounded[, c("overall_precision", "overall_recall")],
    3
  )

additional_classwise_accuracy_rounded <- additional_classwise_accuracy
additional_classwise_accuracy_rounded$classwise_accuracy <-
  round(additional_classwise_accuracy_rounded$classwise_accuracy, 3)

# DGP1 / with_ESCS only, if Table 7 refers to this specification
dgp1_additional_overall_metrics_rounded <- subset(
  additional_overall_metrics_rounded,
  specification == "with_ESCS"
)

dgp1_classwise_accuracy_rounded <- subset(
  additional_classwise_accuracy_rounded,
  specification == "with_ESCS"
)

# Print tables
additional_overall_metrics_rounded
additional_classwise_accuracy_rounded

dgp1_additional_overall_metrics_rounded
dgp1_classwise_accuracy_rounded

# LaTeX-ready tables
knitr::kable(
  additional_overall_metrics_rounded,
  format = "latex",
  booktabs = TRUE,
  caption = "Additional overall precision and recall by model and specification"
)

knitr::kable(
  additional_classwise_accuracy_rounded,
  format = "latex",
  booktabs = TRUE,
  caption = "Additional class-wise accuracy by model and specification"
)

knitr::kable(
  dgp1_additional_overall_metrics_rounded,
  format = "latex",
  booktabs = TRUE,
  caption = "Additional overall precision and recall for DGP1 / with ESCS"
)

knitr::kable(
  dgp1_classwise_accuracy_rounded,
  format = "latex",
  booktabs = TRUE,
  caption = "Additional class-wise accuracy for DGP1 / with ESCS"
)
```




Random Effects - OMERF

```{r}
library(ordinal)
ranef.omerf(om.0,group)
ord.re <- order(om.0$clmm.model$ranef)
ord.re

ranef.omerf(om.1,group)
ord.re2 <- order(om.1$clmm.model$ranef)
ord.re2
```

Random Effects - CLMM

```{r}
ci <- clmm.0$ranef + qnorm(0.975) * sqrt(clmm.0$condVar) %o% c(-1, 1)
ord.re <- order(clmm.0$ranef)
lev <- levels(group)
ci <- ci[order(clmm.0$ranef),]
plot(1:length(lev), clmm.0$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="group", ylab="group effect")
axis(1, at=1:length(lev), labels = lev[ord.re])
axis(2)
for(i in 1:length(lev)) segments(i, ci[i,1], i, ci[i, 2])
abline(h = 0, lty=2)

ci <- clmm.1$ranef + qnorm(0.975) * sqrt(clmm.1$condVar) %o% c(-1, 1)
ord.re <- order(clmm.1$ranef)
lev <- levels(group)
ci <- ci[order(clmm.1$ranef),]
plot(1:length(lev), clmm.1$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="group", ylab="group effect")
axis(1, at=1:length(lev), labels = lev[ord.re])
axis(2)
for(i in 1:length(lev)) segments(i, ci[i,1], i, ci[i, 2])
abline(h = 0, lty=2)
```


```{r}
plot_re_overlay_final <- function(re_omerf, re_clmm, main = NULL) {
  
  stopifnot(length(re_omerf) == length(re_clmm))
  
  ord <- order(re_omerf)
  x <- seq_along(re_omerf)
  
  re_omerf_ord <- re_omerf[ord]
  re_clmm_ord  <- re_clmm[ord]
  
  cor_re <- cor(re_omerf, re_clmm, use = "complete.obs")
  
  col_omerf <- "orange"
  col_clmm  <- "blue"
  
  plot(
    x, re_clmm_ord,
    pch = 16,
    cex = 0.45,
    col = adjustcolor(col_clmm, alpha.f = 0.45),
    xaxt = "n",
    xlab = "Random variable",
    ylab = "Estimated group random effect",
    ylim = range(c(re_omerf_ord, re_clmm_ord), na.rm = TRUE),
    main = main,
    bty = "l"
  )
  
  abline(h = 0, col = "grey40", lty = 2, lwd = 1)
  
  lines(
    x, re_omerf_ord,
    col = col_omerf,
    lwd = 3
  )
  
  axis(
    1,
    at = pretty(x),
    labels = pretty(x)
  )
  
  legend(
    "topleft",
    legend = c("OMERF", "CLMM"),
    col = c(col_omerf, adjustcolor(col_clmm, alpha.f = 0.65)),
    lwd = c(3, NA),
    pch = c(NA, 16),
    pt.cex = c(NA, 0.8),
    bty = "n"
  )
  
  text(
    x = max(x) * 0.70,
    y = max(c(re_omerf_ord, re_clmm_ord), na.rm = TRUE),
    labels = paste0("Correlation = ", round(cor_re, 3)),
    cex = 0.95
  )
}
```


```{r}
plot_re_overlay_final(
  re_omerf = om.1$clmm.model$ranef,
  re_clmm  = clmm.1$ranef
)
```

```{r}
plot_re_overlay_ci <- function(re_omerf, re_clmm, condVar_clmm, main = NULL) {
  
  stopifnot(length(re_omerf) == length(re_clmm))
  stopifnot(length(re_clmm) == length(condVar_clmm))
  
  ord <- order(re_omerf)
  x <- seq_along(re_omerf)
  
  re_omerf_ord <- re_omerf[ord]
  re_clmm_ord  <- re_clmm[ord]
  condVar_ord   <- condVar_clmm[ord]
  
  se_clmm <- sqrt(condVar_ord)
  ci_low  <- re_clmm_ord - qnorm(0.975) * se_clmm
  ci_high <- re_clmm_ord + qnorm(0.975) * se_clmm
  
  cor_re <- cor(re_omerf, re_clmm, use = "complete.obs")
  
  col_omerf <- "#1B9E77"
  col_clmm  <- "#7570B3"
  
  plot(
    x, re_clmm_ord,
    pch = 16,
    cex = 0.40,
    col = adjustcolor(col_clmm, alpha.f = 0.65),
    xaxt = "n",
    xlab = "Random variable",
    ylab = "Estimated group random effect",
    ylim = range(c(re_omerf_ord, ci_low, ci_high), na.rm = TRUE),
    main = main,
    bty = "l"
  )
  
  abline(h = 0, col = "grey40", lty = 2, lwd = 1)
  
  segments(
    x0 = x,
    y0 = ci_low,
    x1 = x,
    y1 = ci_high,
    col = adjustcolor(col_clmm, alpha.f = 0.25),
    lwd = 0.7
  )
  
  points(
    x, re_clmm_ord,
    pch = 16,
    cex = 0.40,
    col = adjustcolor(col_clmm, alpha.f = 0.65)
  )
  
  lines(
    x, re_omerf_ord,
    col = col_omerf,
    lwd = 3
  )
  
  axis(
    1,
    at = pretty(x),
    labels = pretty(x)
  )
  
  legend(
    "topleft",
    legend = c("OMERF", "CLMM", "95% CI for CLMM"),
    col = c(col_omerf, adjustcolor(col_clmm, alpha.f = 0.65), adjustcolor(col_clmm, alpha.f = 0.25)),
    lwd = c(3, NA, 0.7),
    pch = c(NA, 16, NA),
    bty = "n"
  )
  
  text(
    x = max(x) * 0.70,
    y = max(c(re_omerf_ord, ci_high), na.rm = TRUE),
    labels = paste0("Correlation = ", round(cor_re, 3)),
    cex = 0.95
  )
}
```

```{r}
plot_re_overlay_ci(
  re_omerf = om.1$clmm.model$ranef,
  re_clmm = clmm.1$ranef,
  condVar_clmm = clmm.1$condVar
)
```


```{r}
plot_re_overlay_ci <- function(re_omerf, re_clmm, condVar_omerf, main = NULL) {
  
  stopifnot(length(re_omerf) == length(re_clmm))
  stopifnot(length(re_omerf) == length(condVar_omerf))
  
  ord <- order(re_omerf)
  x <- seq_along(re_omerf)
  
  re_omerf_ord  <- re_omerf[ord]
  re_clmm_ord   <- re_clmm[ord]
  condVar_ord   <- condVar_omerf[ord]
  
  se_omerf <- sqrt(condVar_ord)
  ci_low   <- re_omerf_ord - qnorm(0.975) * se_omerf
  ci_high  <- re_omerf_ord + qnorm(0.975) * se_omerf
  
  cor_re <- cor(re_omerf, re_clmm, use = "complete.obs")
  
  col_omerf <- "#1B9E77"
  col_clmm  <- "#7570B3"
  
  plot(
    x, re_clmm_ord,
    pch = 16,
    cex = 0.40,
    col = adjustcolor(col_clmm, alpha.f = 0.65),
    xaxt = "n",
    xlab = "Random variable",
    ylab = "Estimated group random effect",
    ylim = range(c(ci_low, ci_high, re_clmm_ord), na.rm = TRUE),
    main = main,
    bty = "l"
  )
  
  abline(h = 0, col = "grey40", lty = 2, lwd = 1)
  
  segments(
    x0 = x,
    y0 = ci_low,
    x1 = x,
    y1 = ci_high,
    col = adjustcolor(col_omerf, alpha.f = 0.25),
    lwd = 0.7
  )
  
  lines(
    x,
    re_omerf_ord,
    col = col_omerf,
    lwd = 3
  )
  
  points(
    x,
    re_clmm_ord,
    pch = 16,
    cex = 0.40,
    col = adjustcolor(col_clmm, alpha.f = 0.65)
  )
  
  axis(
    1,
    at = pretty(x),
    labels = pretty(x)
  )
  
  legend(
    "topleft",
    legend = c("OMERF", "CLMM", "95% CI for OMERF"),
    col = c(
      col_omerf,
      adjustcolor(col_clmm, alpha.f = 0.65),
      adjustcolor(col_omerf, alpha.f = 0.25)
    ),
    lwd = c(3, NA, 0.7),
    pch = c(NA, 16, NA),
    bty = "n"
  )
  
  text(
    x = max(x) * 0.70,
    y = max(c(ci_high, re_clmm_ord), na.rm = TRUE),
    labels = paste0("Correlation = ", round(cor_re, 3)),
    cex = 0.95
  )
}

plot_re_overlay_ci(
  re_omerf = om.1$clmm.model$ranef,
  re_clmm = clmm.1$ranef,
  condVar_omerf = om.1$clmm.model$condVar
)
```

