---
title: "model_studenti"
output: html_document
date: "2024-01-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "D:/magistrale/OMERF/Def_files/dati")
```

Read the dataset, create datasets for training and testing and import the omerf function and its methods

```{r}
source("OMERF_new.R")
source("ord_class_index.R")
source('index.R')
studenti <- read.csv("student_ita.csv", sep = ",", dec = ".") #10552
studenti <- studenti[,-1]

studenti$mate9[which(studenti$mate9=="6")]="8"
studenti$mate9[which(studenti$mate9=="5")]="7"
studenti$mate9[which(studenti$mate9=="4")]="6"
studenti$mate9[which(studenti$mate9=="3")]="5"
studenti$mate9[which(studenti$mate9=="2")]="4"
studenti$mate9[which(studenti$mate9=="1c")]="3"
studenti$mate9[which(studenti$mate9=="1b")]="2"
studenti$mate9[which(studenti$mate9=="1a")]="1"

studenti$mate3[which(studenti$mate3=="high")]="3"
studenti$mate3[which(studenti$mate3=="medium")]="2"
studenti$mate3[which(studenti$mate3=="low")]="1"

na=rep(0,39)
for (i in 1:39) {
  na[i]=sum(is.na(studenti[,i]))
}
na

studenti <- na.omit(studenti) #7833

#keep schools with at least 10 students
school_counts=table(studenti$school_ID) #340 schools
selected_sch <- names(school_counts[school_counts >= 10]) #293 schools
studenti_new <- studenti[studenti$school_ID %in% selected_sch, ]

studenti_new$grade <- as.factor(studenti_new$grade)
studenti_new$gender <- as.factor(studenti_new$gender)
studenti_new$immig <- as.factor(studenti_new$immig)
#random effects
studenti_new$school_ID <- as.factor(studenti_new$school_ID) 
#responses
studenti_new$mate9=as.factor(studenti_new$mate9)
studenti_new$mate3=as.factor(studenti_new$mate3)

set.seed(1999)

library(caret)
split_indices <- createDataPartition(studenti_new$mate9, p = 0.80, list = FALSE)
data_test_orig <- studenti_new[-split_indices, ]
# "school_ID", "stud_ID", "grade", "gender", "immig", "video_games", "internet_quality", "internet_availability", "SCHRISK",
# "BULLIED", "BELONG", "COOPAGR", "TEACHSUP", "FAMSUP", "PERSEVAGR", "ASSERAGR", "EMPATAGR", "EMOCOAGR", "STRESAGR",
# "CURIOAGR", "math_time", "study_time", "MISCED", "FISCED", "HISCED", "ESCS", "PV1MATH", "PV2MATH", "PV3MATH",
# "PV4MATH", "PV5MATH", "PV6MATH", "PV7MATH", "PV8MATH", "PV9MATH", "PV10MATH", "mate", "mate9", "mate3"

data_test <- data_test_orig[,c("grade", "gender", "immig", "video_games", "internet_quality", "internet_availability", "SCHRISK", "BULLIED", "BELONG", "COOPAGR", "TEACHSUP", "FAMSUP", "PERSEVAGR", "ASSERAGR", "EMPATAGR", "EMOCOAGR", "STRESAGR", "CURIOAGR", "study_time", "HISCED", "ESCS")] #"MISCED", "FISCED", "math_time"
studenti_new <- studenti_new[split_indices, ]


y_test_orig=data_test_orig$mate9 #mate3
y=studenti_new$mate9
cov=studenti_new[,c("grade", "gender", "immig", "video_games", "internet_quality", "internet_availability", "SCHRISK", "BULLIED", "BELONG", "COOPAGR", "TEACHSUP", "FAMSUP", "PERSEVAGR", "ASSERAGR", "EMPATAGR", "EMOCOAGR", "STRESAGR", "CURIOAGR", "study_time", "HISCED", "ESCS")]
group=studenti_new$school_ID

```

CLM

```{r}
library(ordinal)
clm.data= cbind(y,cov)
clm.0=clm(y ~ grade+gender+immig+video_games+internet_quality+internet_availability+SCHRISK+BULLIED+BELONG+COOPAGR+TEACHSUP+FAMSUP+PERSEVAGR+ASSERAGR+EMPATAGR+EMOCOAGR+STRESAGR+CURIOAGR+study_time+HISCED, data=clm.data, link='logit')
summary(clm.0)

clm.1=clm(y ~ grade+gender+immig+video_games+internet_quality+internet_availability+SCHRISK+BULLIED+BELONG+COOPAGR+TEACHSUP+FAMSUP+PERSEVAGR+ASSERAGR+EMPATAGR+EMOCOAGR+STRESAGR+CURIOAGR+study_time+HISCED+ESCS, data=clm.data, link='logit')
summary(clm.1)

# If type = "cum.prob" or type = "linear.predictor" there will be two sets of predictions, standard errors and intervals;
# one for j and one for j-1 (in the usual notation) where j = 1, ..., J index the response classes.
# TEST
mu_clm_t.0=predict(clm.0,data_test)$fit
lev=levels(clm.data$y)
names(mu_clm_t.0) = lev
y_clm_t.0 <- as.numeric(names(mu_clm_t.0)[apply(mu_clm_t.0, 1, which.max)])
prob_t.0=predict(clm.0,data_test,type = "cum.prob")[1]
prob_clm_t.0=prob_t.0$cprob1
prob_clm_t.0[which(prob_clm_t.0==1)]=0.9999
eta_clm_t.0=qlogis(prob_clm_t.0)

mu_clm_t.1=predict(clm.1,data_test)$fit
lev=levels(clm.data$y)
names(mu_clm_t.1) = lev
y_clm_t.1 <- as.numeric(names(mu_clm_t.1)[apply(mu_clm_t.1, 1, which.max)])
prob_t.1=predict(clm.1,data_test,type = "cum.prob")[1]
prob_clm_t.1=prob_t.1$cprob1
prob_clm_t.1[which(prob_clm_t.1==1)]=0.9999
eta_clm_t.1=qlogis(prob_clm_t.1)

```


CLMM

```{r}
forest.data=cbind(clm.data,group)
clmm.data=forest.data
clmm.0=clmm(y ~ grade+gender+immig+video_games+internet_quality+internet_availability+SCHRISK+BULLIED+BELONG+COOPAGR+TEACHSUP+FAMSUP+PERSEVAGR+ASSERAGR+EMPATAGR+EMOCOAGR+STRESAGR+CURIOAGR+study_time+HISCED+(1|group), link='logit', data=clmm.data, Hess=TRUE, control=clmm.control(maxLineIter = 200, maxIter=500, grtol=1e-4))
summary(clmm.0)

clmm.1=clmm(y ~ grade+gender+immig+video_games+internet_quality+internet_availability+SCHRISK+BULLIED+BELONG+COOPAGR+TEACHSUP+FAMSUP+PERSEVAGR+ASSERAGR+EMPATAGR+EMOCOAGR+STRESAGR+CURIOAGR+study_time+HISCED+ESCS+(1|group), link='logit', data=clmm.data, Hess=TRUE, control=clmm.control(maxLineIter = 200, maxIter=500, grtol=1e-4))
summary(clmm.1)

# TEST
data_test=cbind(data_test,data_test_orig$school_ID)
names(data_test)[dim(data_test)[2]]='group'

eta_clmm_t.0=as.data.frame(matrix(0, dim(data_test)[1], length(lev)))
mu_clmm_t.0=as.data.frame(matrix(0, dim(data_test)[1], length(lev)))
names(mu_clmm_t.0) = lev
names(eta_clmm_t.0) = lev
for (j in lev) {
  for (i in 1:dim(data_test)[1]) {
    if (j==lev[1]) {
      eta_clmm_t.0[i,j]=as.numeric(clmm.0$Theta[which(lev==j)]) - ifelse(data_test$grade[i]==10, clmm.0$beta[1], ifelse(data_test$grade[i]==11,clmm.0$beta[2],0)) - ifelse(data_test$gender[i]==1, clmm.0$beta[3], 0) - ifelse(data_test$immig[i]==1, clmm.0$beta[4], ifelse(data_test$immig[i]==2,clmm.0$beta[5],0)) - data_test$video_games[i] * clmm.0$beta[6] - data_test$internet_quality[i] * clmm.0$beta[7] - data_test$internet_availability[i] * clmm.0$beta[8] - data_test$SCHRISK[i] * clmm.0$beta[9] - data_test$BULLIED[i] * clmm.0$beta[10] - data_test$BELONG[i] * clmm.0$beta[11] - data_test$COOPAGR[i] * clmm.0$beta[12] - data_test$TEACHSUP[i] * clmm.0$beta[13] - data_test$FAMSUP[i] * clmm.0$beta[14] - data_test$PERSEVAGR[i] * clmm.0$beta[15] - data_test$ASSERAGR[i] * clmm.0$beta[16] - data_test$EMPATAGR[i] * clmm.0$beta[17] - data_test$EMOCOAGR[i] * clmm.0$beta[18] - data_test$STRESAGR[i] * clmm.0$beta[19] - data_test$CURIOAGR[i] * clmm.0$beta[20] - data_test$study_time[i] * clmm.0$beta[21] - data_test$HISCED[i] * clmm.0$beta[22] - clmm.0$ranef[data_test$group[i]]
      mu_clmm_t.0[i,j]=plogis(eta_clmm_t.0[i,j])
    } else if(j==lev[length(lev)]) {
      eta_clmm_t.0[i,j]=qlogis(0.999)
      mu_clmm_t.0[i,j]=1 - plogis(as.numeric(clmm.0$Theta[which(lev==j)-1]) - ifelse(data_test$grade[i]==10, clmm.0$beta[1], ifelse(data_test$grade[i]==11,clmm.0$beta[2],0)) - ifelse(data_test$gender[i]==1, clmm.0$beta[3], 0) - ifelse(data_test$immig[i]==1, clmm.0$beta[4], ifelse(data_test$immig[i]==2,clmm.0$beta[5],0)) - data_test$video_games[i] * clmm.0$beta[6] - data_test$internet_quality[i] * clmm.0$beta[7] - data_test$internet_availability[i] * clmm.0$beta[8] - data_test$SCHRISK[i] * clmm.0$beta[9] - data_test$BULLIED[i] * clmm.0$beta[10] - data_test$BELONG[i] * clmm.0$beta[11] - data_test$COOPAGR[i] * clmm.0$beta[12] - data_test$TEACHSUP[i] * clmm.0$beta[13] - data_test$FAMSUP[i] * clmm.0$beta[14] - data_test$PERSEVAGR[i] * clmm.0$beta[15] - data_test$ASSERAGR[i] * clmm.0$beta[16] - data_test$EMPATAGR[i] * clmm.0$beta[17] - data_test$EMOCOAGR[i] * clmm.0$beta[18] - data_test$STRESAGR[i] * clmm.0$beta[19] - data_test$CURIOAGR[i] * clmm.0$beta[20] - data_test$study_time[i] * clmm.0$beta[21] - data_test$HISCED[i] * clmm.0$beta[22] - clmm.0$ranef[data_test$group[i]])
    } else {
      eta_clmm_t.0[i,j]=as.numeric(clmm.0$Theta[which(lev==j)]) - ifelse(data_test$grade[i]==10, clmm.0$beta[1], ifelse(data_test$grade[i]==11,clmm.0$beta[2],0)) - ifelse(data_test$gender[i]==1, clmm.0$beta[3], 0) - ifelse(data_test$immig[i]==1, clmm.0$beta[4], ifelse(data_test$immig[i]==2,clmm.0$beta[5],0)) - data_test$video_games[i] * clmm.0$beta[6] - data_test$internet_quality[i] * clmm.0$beta[7] - data_test$internet_availability[i] * clmm.0$beta[8] - data_test$SCHRISK[i] * clmm.0$beta[9] - data_test$BULLIED[i] * clmm.0$beta[10] - data_test$BELONG[i] * clmm.0$beta[11] - data_test$COOPAGR[i] * clmm.0$beta[12] - data_test$TEACHSUP[i] * clmm.0$beta[13] - data_test$FAMSUP[i] * clmm.0$beta[14] - data_test$PERSEVAGR[i] * clmm.0$beta[15] - data_test$ASSERAGR[i] * clmm.0$beta[16] - data_test$EMPATAGR[i] * clmm.0$beta[17] - data_test$EMOCOAGR[i] * clmm.0$beta[18] - data_test$STRESAGR[i] * clmm.0$beta[19] - data_test$CURIOAGR[i] * clmm.0$beta[20] - data_test$study_time[i] * clmm.0$beta[21] - data_test$HISCED[i] * clmm.0$beta[22] - clmm.0$ranef[data_test$group[i]]
      mu_clmm_t.0[i,j]=plogis(eta_clmm_t.0[i,j]) -
        plogis(as.numeric(clmm.0$Theta[which(lev==j)-1]) - ifelse(data_test$grade[i]==10, clmm.0$beta[1], ifelse(data_test$grade[i]==11,clmm.0$beta[2],0)) - ifelse(data_test$gender[i]==1, clmm.0$beta[3], 0) - ifelse(data_test$immig[i]==1, clmm.0$beta[4], ifelse(data_test$immig[i]==2,clmm.0$beta[5],0)) - data_test$video_games[i] * clmm.0$beta[6] - data_test$internet_quality[i] * clmm.0$beta[7] - data_test$internet_availability[i] * clmm.0$beta[8] - data_test$SCHRISK[i] * clmm.0$beta[9] - data_test$BULLIED[i] * clmm.0$beta[10] - data_test$BELONG[i] * clmm.0$beta[11] - data_test$COOPAGR[i] * clmm.0$beta[12] - data_test$TEACHSUP[i] * clmm.0$beta[13] - data_test$FAMSUP[i] * clmm.0$beta[14] - data_test$PERSEVAGR[i] * clmm.0$beta[15] - data_test$ASSERAGR[i] * clmm.0$beta[16] - data_test$EMPATAGR[i] * clmm.0$beta[17] - data_test$EMOCOAGR[i] * clmm.0$beta[18] - data_test$STRESAGR[i] * clmm.0$beta[19] - data_test$CURIOAGR[i] * clmm.0$beta[20] - data_test$study_time[i] * clmm.0$beta[21] - data_test$HISCED[i] * clmm.0$beta[22] - clmm.0$ranef[data_test$group[i]])
    }
  }

}

max_mu_clmm_t.0 <- apply(mu_clmm_t.0, 1, max)
y_clmm_t.0 <- names(mu_clmm_t.0)[apply(mu_clmm_t.0, 1, which.max)]


eta_clmm_t.1=as.data.frame(matrix(0, dim(data_test)[1], length(lev)))
mu_clmm_t.1=as.data.frame(matrix(0, dim(data_test)[1], length(lev)))
names(mu_clmm_t.1) = lev
names(eta_clmm_t.1) = lev
for (j in lev) {
  for (i in 1:dim(data_test)[1]) {
    if (j==lev[1]) {
      eta_clmm_t.1[i,j]=as.numeric(clmm.1$Theta[which(lev==j)]) - ifelse(data_test$grade[i]==10, clmm.1$beta[1], ifelse(data_test$grade[i]==11,clmm.1$beta[2],0)) - ifelse(data_test$gender[i]==1, clmm.1$beta[3], 0) - ifelse(data_test$immig[i]==1, clmm.1$beta[4], ifelse(data_test$immig[i]==2,clmm.1$beta[5],0)) - data_test$video_games[i] * clmm.1$beta[6] - data_test$internet_quality[i] * clmm.1$beta[7] - data_test$internet_availability[i] * clmm.1$beta[8] - data_test$SCHRISK[i] * clmm.1$beta[9] - data_test$BULLIED[i] * clmm.1$beta[10] - data_test$BELONG[i] * clmm.1$beta[11] - data_test$COOPAGR[i] * clmm.1$beta[12] - data_test$TEACHSUP[i] * clmm.1$beta[13] - data_test$FAMSUP[i] * clmm.1$beta[14] - data_test$PERSEVAGR[i] * clmm.1$beta[15] - data_test$ASSERAGR[i] * clmm.1$beta[16] - data_test$EMPATAGR[i] * clmm.1$beta[17] - data_test$EMOCOAGR[i] * clmm.1$beta[18] - data_test$STRESAGR[i] * clmm.1$beta[19] - data_test$CURIOAGR[i] * clmm.1$beta[20] - data_test$study_time[i] * clmm.1$beta[21] - data_test$HISCED[i] * clmm.1$beta[22] - data_test$ESCS[i] * clmm.1$beta[23] - clmm.1$ranef[data_test$group[i]]
      mu_clmm_t.1[i,j]=plogis(eta_clmm_t.1[i,j])
    } else if(j==lev[length(lev)]) {
      eta_clmm_t.1[i,j]=qlogis(0.999)
      mu_clmm_t.1[i,j]=1 - plogis(as.numeric(clmm.1$Theta[which(lev==j)-1]) - ifelse(data_test$grade[i]==10, clmm.1$beta[1], ifelse(data_test$grade[i]==11,clmm.1$beta[2],0)) - ifelse(data_test$gender[i]==1, clmm.1$beta[3], 0) - ifelse(data_test$immig[i]==1, clmm.1$beta[4], ifelse(data_test$immig[i]==2,clmm.1$beta[5],0)) - data_test$video_games[i] * clmm.1$beta[6] - data_test$internet_quality[i] * clmm.1$beta[7] - data_test$internet_availability[i] * clmm.1$beta[8] - data_test$SCHRISK[i] * clmm.1$beta[9] - data_test$BULLIED[i] * clmm.1$beta[10] - data_test$BELONG[i] * clmm.1$beta[11] - data_test$COOPAGR[i] * clmm.1$beta[12] - data_test$TEACHSUP[i] * clmm.1$beta[13] - data_test$FAMSUP[i] * clmm.1$beta[14] - data_test$PERSEVAGR[i] * clmm.1$beta[15] - data_test$ASSERAGR[i] * clmm.1$beta[16] - data_test$EMPATAGR[i] * clmm.1$beta[17] - data_test$EMOCOAGR[i] * clmm.1$beta[18] - data_test$STRESAGR[i] * clmm.1$beta[19] - data_test$CURIOAGR[i] * clmm.1$beta[20] - data_test$study_time[i] * clmm.1$beta[21] - data_test$HISCED[i] * clmm.1$beta[22] - data_test$ESCS[i] * clmm.1$beta[23] - clmm.1$ranef[data_test$group[i]])
    } else {
      eta_clmm_t.1[i,j]=as.numeric(clmm.1$Theta[which(lev==j)]) - ifelse(data_test$grade[i]==10, clmm.1$beta[1], ifelse(data_test$grade[i]==11,clmm.1$beta[2],0)) - ifelse(data_test$gender[i]==1, clmm.1$beta[3], 0) - ifelse(data_test$immig[i]==1, clmm.1$beta[4], ifelse(data_test$immig[i]==2,clmm.1$beta[5],0)) - data_test$video_games[i] * clmm.1$beta[6] - data_test$internet_quality[i] * clmm.1$beta[7] - data_test$internet_availability[i] * clmm.1$beta[8] - data_test$SCHRISK[i] * clmm.1$beta[9] - data_test$BULLIED[i] * clmm.1$beta[10] - data_test$BELONG[i] * clmm.1$beta[11] - data_test$COOPAGR[i] * clmm.1$beta[12] - data_test$TEACHSUP[i] * clmm.1$beta[13] - data_test$FAMSUP[i] * clmm.1$beta[14] - data_test$PERSEVAGR[i] * clmm.1$beta[15] - data_test$ASSERAGR[i] * clmm.1$beta[16] - data_test$EMPATAGR[i] * clmm.1$beta[17] - data_test$EMOCOAGR[i] * clmm.1$beta[18] - data_test$STRESAGR[i] * clmm.1$beta[19] - data_test$CURIOAGR[i] * clmm.1$beta[20] - data_test$study_time[i] * clmm.1$beta[21] - data_test$HISCED[i] * clmm.1$beta[22] - data_test$ESCS[i] * clmm.1$beta[23] - clmm.1$ranef[data_test$group[i]]
      mu_clmm_t.1[i,j]=plogis(eta_clmm_t.1[i,j]) -
        plogis(as.numeric(clmm.1$Theta[which(lev==j)-1]) - ifelse(data_test$grade[i]==10, clmm.1$beta[1], ifelse(data_test$grade[i]==11,clmm.1$beta[2],0)) - ifelse(data_test$gender[i]==1, clmm.1$beta[3], 0) - ifelse(data_test$immig[i]==1, clmm.1$beta[4], ifelse(data_test$immig[i]==2,clmm.1$beta[5],0)) - data_test$video_games[i] * clmm.1$beta[6] - data_test$internet_quality[i] * clmm.1$beta[7] - data_test$internet_availability[i] * clmm.1$beta[8] - data_test$SCHRISK[i] * clmm.1$beta[9] - data_test$BULLIED[i] * clmm.1$beta[10] - data_test$BELONG[i] * clmm.1$beta[11] - data_test$COOPAGR[i] * clmm.1$beta[12] - data_test$TEACHSUP[i] * clmm.1$beta[13] - data_test$FAMSUP[i] * clmm.1$beta[14] - data_test$PERSEVAGR[i] * clmm.1$beta[15] - data_test$ASSERAGR[i] * clmm.1$beta[16] - data_test$EMPATAGR[i] * clmm.1$beta[17] - data_test$EMOCOAGR[i] * clmm.1$beta[18] - data_test$STRESAGR[i] * clmm.1$beta[19] - data_test$CURIOAGR[i] * clmm.1$beta[20] - data_test$study_time[i] * clmm.1$beta[21] - data_test$HISCED[i] * clmm.1$beta[22] - data_test$ESCS[i] * clmm.1$beta[23] - clmm.1$ranef[data_test$group[i]])
    }
  }

}

max_mu_clmm_t.1 <- apply(mu_clmm_t.1, 1, max)
y_clmm_t.1 <- names(mu_clmm_t.1)[apply(mu_clmm_t.1, 1, which.max)]

```

ORDINAL FOREST

```{r}
library(ordinalForest)
ordfor.data=forest.data
ordforest.0 <- ordfor(depvar = 'y', perffunction = 'probability', ordfor.data[, -which(names(ordfor.data) %in% c("ESCS"))])

ordforest.1 <- ordfor(depvar = 'y', perffunction = 'probability', ordfor.data)

#TEST
mu_ord_t.0 <- predict(ordforest.0, newdata=data_test)$classprobs
max_mu_ord_t.0 <- apply(mu_ord_t.0, 1, max)
y_ord_t.0 <- predict(ordforest.0, newdata=data_test)$ypred

mu_ord_t.1 <- predict(ordforest.1, newdata=data_test)$classprobs
max_mu_ord_t.1 <- apply(mu_ord_t.1, 1, max)
y_ord_t.1 <- predict(ordforest.1, newdata=data_test)$ypred

```

OMERF

```{r}
om.0 = omerf(y, cov[, -which(names(cov) %in% c("ESCS"))], group)
summary.omerf(om.0)
om.0$clmm.model$ST
VarCorr(om.0$clmm.model)

om.1 = omerf(y, cov, group)
summary.omerf(om.1)
om.1$clmm.model$ST
VarCorr(om.1$clmm.model)

#varimp
library(caret)
varImp(om.0$forest.model)
importance(om.0$forest.model, type=1)
importance(om.0$forest.model, type=2)
varImpPlot(om.0$forest.model)

varImp(om.1$forest.model)
importance(om.1$forest.model, type=1)
importance(om.1$forest.model, type=2)
varImpPlot(om.1$forest.model)

# TEST
y_omerf_t.0 = predict.omerf(om.0, y, data_test, data_test$group, type='response')
mu_omerf_t.0=predict.omerf(om.0, y, data_test, data_test$group, type='mu')
max_mu_omerf_t.0 = apply(mu_omerf_t.0, 1, max)
eta_omerf_t.0=predict.omerf(om.0, y, data_test, data_test$group, type='eta')

y_omerf_t.1 = predict.omerf(om.1, y, data_test, data_test$group, type='response')
mu_omerf_t.1=predict.omerf(om.1, y, data_test, data_test$group, type='mu')
max_mu_omerf_t.1 = apply(mu_omerf_t.1, 1, max)
eta_omerf_t.1=predict.omerf(om.1, y, data_test, data_test$group, type='eta')
```

Random Effects - OMERF

```{r}
ranef.omerf(om.0,group)
ord.re <- order(om.0$clmm.model$ranef)
ord.re

ranef.omerf(om.1,group)
ord.re2 <- order(om.1$clmm.model$ranef)
ord.re2
```

performance measures

```{r}
library(pdfCluster)
library(psych)
results.acc=matrix(nrow=2, ncol=4, data=rep(0,8))
results.mse=matrix(nrow=2, ncol=4, data=rep(0,8))
results.oc=matrix(nrow=2, ncol=4, data=rep(0,8))
results.ari=matrix(nrow=2, ncol=4, data=rep(0,8))
results.ck=matrix(nrow=2, ncol=4, data=rep(0,8))
results.newi=matrix(nrow=2, ncol=4, data=rep(0,8))
colnames(results.acc)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.mse)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.oc)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.ari)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.ck)=c('clm', 'clmm','ordforest', 'omerf')
colnames(results.newi)=c('clm', 'clmm','ordforest', 'omerf')

y_test=as.numeric(y_test_orig)
y_test_newi=as.numeric(y_test_orig)
lev=levels(clm.data$y)


results.acc[1,1]=sum(y_test==as.numeric(y_clm_t.0))/length(y_test)
results.mse[1,1]=mean((y_test - as.numeric(y_clm_t.0))^2)
cm_clm <- table(y_test, as.numeric(y_clm_t.0))
cm_clm
num_classes_clm <- max(nrow(cm_clm), ncol(cm_clm))
cm_clm2 <- matrix(0, nrow = num_classes_clm, ncol = num_classes_clm)
rownames(cm_clm2) <- colnames(cm_clm2) <- lev
cm_clm2[rownames(cm_clm), colnames(cm_clm)] <- cm_clm[rownames(cm_clm), colnames(cm_clm)]
results.oc[1,1]=OrdinalClassificationIndex(cm_clm2, dim(cm_clm2)[1])
results.ari[1,1]=adj.rand.index(y_test, as.numeric(y_clm_t.0))
results.ck[1,1]=cohen.kappa(x=cbind(y_test,as.numeric(y_clm_t.0)))$kappa
results.newi[1,1]=newindex(mu_clm_t.0,y_test_newi,num_classes_clm)$norm.index


results.acc[2,1]=sum(y_test==as.numeric(y_clm_t.1))/length(y_test)
results.mse[2,1]=mean((y_test - as.numeric(y_clm_t.1))^2)
cm_clm <- table(y_test, as.numeric(y_clm_t.1))
cm_clm
num_classes_clm <- max(nrow(cm_clm), ncol(cm_clm))
cm_clm2 <- matrix(0, nrow = num_classes_clm, ncol = num_classes_clm)
rownames(cm_clm2) <- colnames(cm_clm2) <- lev
cm_clm2[rownames(cm_clm), colnames(cm_clm)] <- cm_clm[rownames(cm_clm), colnames(cm_clm)]
results.oc[2,1]=OrdinalClassificationIndex(cm_clm2, dim(cm_clm2)[1])
results.ari[2,1]=adj.rand.index(y_test, as.numeric(y_clm_t.1))
results.ck[2,1]=cohen.kappa(x=cbind(y_test,as.numeric(y_clm_t.1)))$kappa
results.newi[2,1]=newindex(mu_clm_t.1,y_test_newi,num_classes_clm)$norm.index


results.acc[1,2]=sum(y_test==as.numeric(y_clmm_t.0))/length(y_test)
results.mse[1,2]=mean((y_test - as.numeric(y_clmm_t.0))^2)
cm_clmm <- table(y_test, as.numeric(y_clmm_t.0))
cm_clmm
num_classes_clmm <- max(nrow(cm_clmm), ncol(cm_clmm))
cm_clmm2 <- matrix(0, nrow = num_classes_clmm, ncol = num_classes_clmm)
rownames(cm_clmm2) <- colnames(cm_clmm2) <- lev
cm_clmm2[rownames(cm_clmm), colnames(cm_clmm)] <- cm_clmm[rownames(cm_clmm), colnames(cm_clmm)]
results.oc[1,2]=OrdinalClassificationIndex(cm_clmm2, dim(cm_clmm2)[1])
results.ari[1,2]=adj.rand.index(y_test, as.numeric(y_clmm_t.0))
results.ck[1,2]=cohen.kappa(x=cbind(y_test,as.numeric(y_clmm_t.0)))$kappa
results.newi[1,2]=newindex(mu_clmm_t.0,y_test_newi,num_classes_clmm)$norm.index


results.acc[2,2]=sum(y_test==as.numeric(y_clmm_t.1))/length(y_test)
results.mse[2,2]=mean((y_test - as.numeric(y_clmm_t.1))^2)
cm_clmm <- table(y_test, as.numeric(y_clmm_t.1))
cm_clmm
num_classes_clmm <- max(nrow(cm_clmm), ncol(cm_clmm))
cm_clmm2 <- matrix(0, nrow = num_classes_clmm, ncol = num_classes_clmm)
rownames(cm_clmm2) <- colnames(cm_clmm2) <- lev
cm_clmm2[rownames(cm_clmm), colnames(cm_clmm)] <- cm_clmm[rownames(cm_clmm), colnames(cm_clmm)]
results.oc[2,2]=OrdinalClassificationIndex(cm_clmm2, dim(cm_clmm2)[1])
results.ari[2,2]=adj.rand.index(y_test, as.numeric(y_clmm_t.1))
results.ck[2,2]=cohen.kappa(x=cbind(y_test,as.numeric(y_clmm_t.1)))$kappa
results.newi[2,2]=newindex(mu_clmm_t.1,y_test_newi,num_classes_clmm)$norm.index


results.acc[1,3]=sum(y_test==as.numeric(y_ord_t.0))/length(y_test)
results.mse[1,3]=mean((y_test - as.numeric(y_ord_t.0))^2)
cm_ord <- table(y_test, as.numeric(y_ord_t.0))
cm_ord
num_classes_ord <- max(nrow(cm_ord), ncol(cm_ord))
cm_ord2 <- matrix(0, nrow = num_classes_ord, ncol = num_classes_ord)
rownames(cm_ord2) <- colnames(cm_ord2) <- lev
cm_ord2[rownames(cm_ord), colnames(cm_ord)] <- cm_ord[rownames(cm_ord), colnames(cm_ord)]
results.oc[1,3]=OrdinalClassificationIndex(cm_ord2, dim(cm_ord2)[1])
results.ari[1,3]=adj.rand.index(y_test, as.numeric(y_ord_t.0))
results.ck[1,3]=cohen.kappa(x=cbind(y_test,as.numeric(y_ord_t.0)))$kappa
results.newi[1,3]=newindex(mu_ord_t.0,y_test_newi,num_classes_ord)$norm.index


results.acc[2,3]=sum(y_test==as.numeric(y_ord_t.1))/length(y_test)
results.mse[2,3]=mean((y_test - as.numeric(y_ord_t.1))^2)
cm_ord <- table(y_test, as.numeric(y_ord_t.1))
cm_ord
num_classes_ord <- max(nrow(cm_ord), ncol(cm_ord))
cm_ord2 <- matrix(0, nrow = num_classes_ord, ncol = num_classes_ord)
rownames(cm_ord2) <- colnames(cm_ord2) <- lev
cm_ord2[rownames(cm_ord), colnames(cm_ord)] <- cm_ord[rownames(cm_ord), colnames(cm_ord)]
results.oc[2,3]=OrdinalClassificationIndex(cm_ord2, dim(cm_ord2)[1])
results.ari[2,3]=adj.rand.index(y_test, as.numeric(y_ord_t.1))
results.ck[2,3]=cohen.kappa(x=cbind(y_test,as.numeric(y_ord_t.1)))$kappa
results.newi[2,3]=newindex(mu_ord_t.1,y_test_newi,num_classes_ord)$norm.index


results.acc[1,4]=sum(y_test==as.numeric(y_omerf_t.0))/length(y_test)
results.mse[1,4]=mean((y_test - as.numeric(y_omerf_t.0))^2)
cm_omerf <- table(y_test, as.numeric(y_omerf_t.0))
cm_omerf
num_classes_omerf <- max(nrow(cm_omerf), ncol(cm_omerf))
cm_omerf2 <- matrix(0, nrow = num_classes_omerf, ncol = num_classes_omerf)
rownames(cm_omerf2) <- colnames(cm_omerf2) <- lev
cm_omerf2[rownames(cm_omerf), colnames(cm_omerf)] <- cm_omerf[rownames(cm_omerf), colnames(cm_omerf)]
results.oc[1,4]=OrdinalClassificationIndex(cm_omerf2, dim(cm_omerf2)[1])
results.ari[1,4]=adj.rand.index(y_test, as.numeric(y_omerf_t.0))
results.ck[1,4]=cohen.kappa(x=cbind(y_test,as.numeric(y_omerf_t.0)))$kappa
results.newi[1,4]=newindex(mu_omerf_t.0,y_test_newi,num_classes_omerf)$norm.index


results.acc[2,4]=sum(y_test==as.numeric(y_omerf_t.1))/length(y_test)
results.mse[2,4]=mean((y_test - as.numeric(y_omerf_t.1))^2)
cm_omerf <- table(y_test, as.numeric(y_omerf_t.1))
cm_omerf
num_classes_omerf <- max(nrow(cm_omerf), ncol(cm_omerf))
cm_omerf2 <- matrix(0, nrow = num_classes_omerf, ncol = num_classes_omerf)
rownames(cm_omerf2) <- colnames(cm_omerf2) <- lev
cm_omerf2[rownames(cm_omerf), colnames(cm_omerf)] <- cm_omerf[rownames(cm_omerf), colnames(cm_omerf)]
results.oc[2,4]=OrdinalClassificationIndex(cm_omerf2, dim(cm_omerf2)[1])
results.ari[2,4]=adj.rand.index(y_test, as.numeric(y_omerf_t.1))
results.ck[2,4]=cohen.kappa(x=cbind(y_test,as.numeric(y_omerf_t.1)))$kappa
results.newi[2,4]=newindex(mu_omerf_t.1,y_test_newi,num_classes_omerf)$norm.index


results.acc
results.mse
results.oc
results.ari
results.ck
results.newi
```

PARTIAL PLOT - random forest (da omerf)

```{r}
var.names=c("grade", "gender", "immig", "video_games", "internet_quality", "internet_availability", "SCHRISK", "BULLIED", "BELONG", "COOPAGR", "TEACHSUP", "FAMSUP", "PERSEVAGR", "ASSERAGR", "EMPATAGR", "EMOCOAGR", "STRESAGR", "CURIOAGR", "study_time", "HISCED")
par(mfrow=c(2,4))
for (i in 1:length(var.names)) {
  partialPlot(om.0$forest.model, pred.data=forest.data,x.var=var.names[i],xlab=var.names[i],main='Partial dependence plot')
}
```


```{r}
var.names=c("grade", "gender", "immig", "video_games", "internet_quality", "internet_availability", "SCHRISK", "BULLIED", "BELONG", "COOPAGR", "TEACHSUP", "FAMSUP", "PERSEVAGR", "ASSERAGR", "EMPATAGR", "EMOCOAGR", "STRESAGR", "CURIOAGR", "study_time", "HISCED", "ESCS")
par(mfrow=c(2,4))
for (i in 1:length(var.names)) {
  partialPlot(om.1$forest.model, pred.data=forest.data,x.var=var.names[i],xlab=var.names[i],main='Partial dependence plot')
}
```

Feature importance - iml

```{r}
library("iml")
library("ggplot2")
mod0 <- Predictor$new(om.0$forest.model, data = cov[, -which(names(cov) %in% c("ESCS"))], y = om.0$rf.target)
imp0 <- FeatureImp$new(mod0, loss = "mse")
plot(imp0)
```

```{r}
mod1 <- Predictor$new(om.1$forest.model, data = cov, y = om.1$rf.target)
imp1 <- FeatureImp$new(mod1, loss = "mse")
plot(imp1)
```

PARTIAL PLOT - iml

```{r}

mod01 <- Predictor$new(om.0$forest.model, data = cov[, -which(names(cov) %in% c("ESCS"))])
effs0 <- FeatureEffects$new(mod01)
plot(effs0) #effs0$plot()
```

```{r}
mod11 <- Predictor$new(om.1$forest.model, data = cov)
effs1 <- FeatureEffects$new(mod11)
plot(effs1)
```

